
application:
  lockmanager:
    type: redis
    port: ${REDIS_PORT:6379}
    host: ${REDIS_HOST:localhost}
    release-timeout: 5000
    redis:
      cache-name: circuitBreaker
  itunes:
    url: ${ITUNES_URL:https://itunes.apple.com/search?term={term}&limit={limit}}
  google:
    url: ${GOOGLE_URL:https://www.googleapis.com/books/v1/volumes?q={term}&maxResults={limit}}
  
       
spring:
  profiles:
    active: resilience4j


resilience4j:
    circuitbreaker:
        instances:
            mockService:
                slidingWindowSize: 3
                slidingWindowType: COUNT_BASED
                #waitDurationInOpenState: 5
                waitInterval: 10000
                failureRateThreshold: 50
                permittedNumberOfCallsInHalfOpenState: 5
                registerHealthIndicator: true
                #register-health-indicator: true
                allowHealthIndicatorToFail: true
        configs:
            default:
                registerHealthIndicator: true

management.health.circuitbreakers.enabled: true
management:
  endpoint:
    health:
        show-details: always


   