
application:
  lockmanager:
    type: redis
    port: ${REDIS_PORT:6379}
    host: ${REDIS_HOST:localhost}
    release-timeout: 5000
    redis:
      cache-name: circuitBreaker
  itunes:
    url: https://itunes.aapple.com/search?term={term}&limit={limit}
  google:
    url: https://www.googleapis.com/books/v1/volumes?q={term}&maxResults={limit}
  
       
spring:
  profiles:
    active: resilience4j


   