apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-webclient-deployment
  labels:
    app: webclient-itunesgoogle
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webclient-itunesgoogle  
  template:
    metadata:
      labels:
        app: webclient-itunesgoogle
    spec:
      containers:
        - name: webclient-itunesgoogle
          image: mdymen85/webclient-itunes-google:latest
          ports:
            - containerPort: 8080
